class TraceAppNames:
    trace_application_names = {
        'ActOfWar':                                        ('Act of War: Direct Action', None, 'D3D9'),
        'ActOfWar_HighTreason':                            ('Act of War: High Treason', None, 'D3D9'),
        'AIMII':                                           ('A.I.M. 2: Clan Wars', None, 'D3D8'),
        'AIMRace':                                         ('A.I.M. Racing', None, 'D3D8'),
        'Against the Storm':                               (None, None, 'D3D11'),
        'AlienShooter':                                    ('Alien Shooter', None, 'D3D8'),
        'AN2':                                             ('AquaNox 2: Revelation', None, 'D3D9'),
        'Anno1701AddOn':                                   ('Anno 1701', None, 'D3D9'),
        'Anno4':                                           ('Anno 1404', None, 'D3D9'),
        'Anno4_':                                          ('Anno 1404', None, 'D3D10'),
        'Another World':                                   (None, None, 'D3D8'),
        'AoW3':                                            ('Age of Wonders III', None, 'D3D9'),
        'APGame':                                          ('Alpha Protocol', None, 'D3D9'),
        'APlagueTaleInnocence_x64':                        ('A Plague Tale: Innocence', None, 'D3D11'),
        'Aqua':                                            ('AquaNox', None, 'D3D8'),
        'arma':                                            ('Arma: Armed Assault', None, 'D3D9'),
        'arma2':                                           ('Arma 2', None, 'D3D9Ex'),
        'arma2OA':                                         ('Arma 2: Operation Arrowhead', None, 'D3D9Ex'),
        'Arma3_x64':                                       ('Arma 3', None, 'D3D11'),
        'Armada2':                                         ('Star Trek: Armada II', None, 'D3D8'),
        'AshesEscalation_DX11':                            ('Ashes of the Singularity: Escalation', None, 'D3D11'),
        'AssassinsCreed_Dx9':                              ('Assassin\'s Creed', None, 'D3D9'),
        'AssassinsCreed_Dx10':                             ('Assassin\'s Creed', None, 'D3D10'),
        'AvenColony-Win64-Shipping':                       ('Aven Colony', None, 'D3D11'),
        'AvP_Classic':                                     ('Aliens vs. Predator (2010)', None, 'D3D9'),
        'BattleFleetGothic-Win64-Shipping':                ('Battlefleet Gothic: Armada', None, 'D3D11'),
        'BattlefleetGothic2-Win64-Shipping':               ('Battlefleet Gothic: Armada 2', None, 'D3D11'),
        'BattlefrontII':                                   ('Star Wars: Battlefront II', None, 'D3D9'),
        'Battlefront':                                     ('Star Wars: Battlefront', None, 'D3D9'),
        'battlezone2':                                     ('Battlezone: Combat Commander', None, 'D3D11'),
        'BBCT':                                            ('BlazBlue: Calamity Trigger', None, 'D3D9'),
        'bg3_dx11':                                        ('Baldur\'s Gate 3', None, 'D3D11'),
        'BGE':                                             ('Beyond Good & Evil', None, 'D3D9'),
        'Biomutant-Win64-Shipping':                        ('Biomutant', None, 'D3D11'),
        'Bioshock':                                        ('BioShock', None, 'D3D9'),
        'Bioshock_':                                       ('BioShock', None, 'D3D10'),
        'Bioshock2':                                       ('BioShock 2', None, 'D3D9'),
        'Bioshock2_':                                      ('BioShock 2', None, 'D3D10'),
        'Bloodshed':                                       (None, None, 'D3D11'),
        'Blowout':                                         ('BlowOut', None, 'D3D8'),
        'BLUE PRINCE':                                     ('Blue Prince', None, 'D3D11'),
        'bms':                                             ('Black Mesa', None, 'D3D9Ex'),
        'bo2':                                             ('Legacy of Kain: Blood Omen 2', None, 'D3D8'),
        'Boltgun-Win64-Shipping':                          ('Warhammer 40,000: Boltgun', None, 'D3D11'),
        'BoundByFlame':                                    ('Bound by Flame', None, 'D3D9'),
        'braid64_d3d11_final':                             ('Braid Anniversary Edition', None, 'D3D11'),
        'Brawls':                                          ('Lego Brawls', None, 'D3D11'),
        'Brothers':                                        ('Brothers: A Tale of Two Sons', None, 'D3D9'),
        'BSTSD':                                           ('Broken Sword 3: The Sleeping Dragon', None, 'D3D8'),
        'Carmageddon_Max_Damage':                          ('Carmageddon: Max Damage', None, 'D3D11'),
        'Castlestrike':                                    ('Castle Strike', None, 'D3D8'),
        'CCE':                                             ('Close Combat: Panthers in the Fog', None, 'D3D9'),
        'Chessmaster':                                     ('Chessmaster 9000', None, 'D3D8'),
        'Civ4Warlords':                                    ('Sid Meier\'s Civilization IV', None, 'D3D9'),
        'CivCity Rome':                                    ('CivCity: Rome', None, 'D3D9'),
        'CNC3EP1':                                         ('Command & Conquer 3: Tiberium Wars', None, 'D3D9'),
        'CoD2SP_s':                                        ('Call of Duty 2', None, 'D3D9'),
        'CoDWaW':                                          ('Call of Duty: World at War', None, 'D3D9'),
        'CoJ':                                             ('Call of Juarez', None, 'D3D9'),
        'CoJ_DX10':                                        ('Call of Juarez', None, 'D3D10'),
        'ColdWarAssault':                                  ('Arma: Cold War Assault', None, 'D3D8'),
        'Commandos3':                                      ('Commandos 3: Destination Berlin', None, 'D3D8'),
        'Control_DX11':                                    ('Control', None, 'D3D11'),
        'Crysis':                                          (None, None, 'D3D9'),
        'Crysis_':                                         (None, None, 'D3D10'),
        'cs2':                                             ('Counter-Strike 2', None, 'D3D11'),
        'Cuphead':                                         (None, None, 'D3D11'),
        'Curse':                                           ('Curse: The Eye of Isis', None, 'D3D8'),
        'dangerouswaters':                                 ('Dangerous Waters', None, 'D3D8'),
        'DAOrigins':                                       ('Dragon Age: Origins', None, 'D3D9'),
        'DDDA':                                            ('Dragon\'s Dogma: Dark Arisen', None, 'D3D9'),
        'Dead Space':                                      (None, None, 'D3D9'),
        'defiance':                                        ('Legacy of Kain: Defiance', None, 'D3D9'),
        'Demonstone':                                      ('Forgotten Realms: Demon Stone', None, 'D3D9'),
        'DesertsOfKharak':                                 ('Homeworld: Deserts of Kharak', None, 'D3D11'),
        'DesertStorm':                                     ('Conflict: Desert Storm', None, 'D3D8'),
        'div':                                             ('Beyond Divinity', None, 'D3D9'),
        'Divinity2':                                       ('Divinity II: Developer\'s Cut', None, 'D3D9'),
        'dontstarve':                                      ('Don\'t Starve', None, 'D3D9Ex'),
        'DOW2':                                            ('Warhammer 40,000: Dawn of War II', None, 'D3D9'),
        'DragonAgeInquisition':                            ('Dragon Age: Inquisition', None, 'D3D11'),
        'dragonnest':                                      ('Dragon Nest', None, 'D3D9'),
        'DragonCommander':                                 ('Divinity: Dragon Commander', None, 'D3D9'),
        'Dragonshard':                                     ('Dungeons & Dragons: Dragonshard', None, 'D3D9'),
        'Drake':                                           ('Drake of the 99 Dragons', None, 'D3D8'),
        'drakensang':                                      ('Drakensang: The Dark Eye', None, 'D3D9'),
        'dreamfall':                                       ('Dreamfall: The Longest Journey', None, 'D3D9'),
        'Dredd':                                           ('Judge Dredd: Dredd vs. Death', None, 'D3D8'),
        'Driftland-Win64-Shipping':                        ('Driftland: The Magic Revival', None, 'D3D11'),
        'DukeForever':                                     ('Duke Nukem Forever: Restoration Project', None, 'D3D8'),
        'DungeonSiege2':                                   ('Dungeon Siege II', None, 'D3D9'),
        'Dungeon Siege III':                               (None, None, 'D3D9'),
        'DX2Main':                                         ('Deus Ex: Invisible War', None, 'D3D8'),
        'DXHRDC':                                          ('Deus Ex: Human Revolution - Director\'s Cut', None, 'D3D11'),
        'DyingLightGame':                                  ('Dying Light', None, 'D3D11'),
        'E5':                                              ('Brigade E5: New Jagged Union', None, 'D3D8'),
        'ed6_win':                                         ('The Legend of Heroes: Trails in the Sky', None, 'D3D8'),
        'Eden':                                            ('Project Eden', None, 'D3D8'),
        'EE2X':                                            ('Empire Earth II', None, 'D3D8'),
        'EE3':                                             ('Empire Earth III', None, 'D3D9'),
        'Empires_DMW':                                     ('Empires: Dawn of the Modern World', None, 'D3D8'),
        'Enclave':                                         (None, None, 'D3D8'),
        'engine':                                          ('Cossacks II: Battle for Europe', None, 'D3D8'),
        'engine_':                                         ('Alexander', None, 'D3D8'),
        'EoCApp':                                          ('Divinity: Original Sin', None, 'D3D9'),
        'EoCApp_':                                         ('Divinity: Original Sin - Enhanced Edition', None, 'D3D11'),
        'EoCApp__':                                        ('Divinity: Original Sin II', None, 'D3D11'),
        'EoCApp___':                                       ('Divinity: Original Sin II - Definitive Edition', None, 'D3D11'),
        'eqgame':                                          ('EverQuest', None, 'D3D9'),
        'eqgame_':                                         ('EverQuest', None, 'D3D11'),
        'ES2-Win64-Shipping':                              ('Everspace 2', None, 'D3D11'),
        'eso64':                                           ('The Elder Scrolls Online', None, 'D3D11'),
        'Europa1400Gold_TL':                               ('Europa 1400: The Guild', None, 'D3D8'),
        'EYE':                                             ('E.Y.E: Divine Cybermancy', None, 'D3D9'),
        'EXAPUNKS':                                        ('Exapunks', None, 'D3D11'),
        'Fallout3':                                        ('Fallout 3', None, 'D3D9'),
        'FalloutNV':                                       ('Fallout: New Vegas', None, 'D3D9'),
        'FantasyMapSimulator':                             ('Fantasy Map Simulator', None, 'D3D11'), # No PCGW page yet
        'FarCry2':                                         ('Far Cry 2', None, 'D3D9'), # Also uses D3D9Ex for some queries
        'Fate':                                            ('FATE: The Cursed King', None, 'D3D8'),
        'FEAR':                                            ('F.E.A.R.', None, 'D3D9'),
        'fforce':                                          ('Freedom Force', None, 'D3D8'),
        'fifa2003':                                        ('FIFA Football 2003', None, 'D3D8'),
        'FlatOut2':                                        ('FlatOut 2', None, 'D3D9'),
        'flatout':                                         ('FlatOut', None, 'D3D9'),
        'forces':                                          ('Incoming Forces', None, 'D3D8'),
        'Freedom':                                         ('Freedom Fighters', None, 'D3D9'),
        'freelancer':                                      ('Freelancer', None, 'D3D8'),
        'FruitNinja':                                      ('Fruit Ninja', None, 'D3D9'),
        'FSD-Win64-Shipping':                              ('Deep Rock Galactic', None, 'D3D11'),
        'GalCiv2':                                         ('Galactic Civilizations II', None, 'D3D9'),
        'gameBFME':                                        ('The Lord of the Rings: The Battle for Middle-earth', None, 'D3D9'),
        'GameBlitzkrieg':                                  ('Blitzkrieg', None, 'D3D8'),
        'GameDesertLaw':                                   ('Desert Law', None, 'D3D8'),
        'GameHaegemonia':                                  ('Haegemonia: Legions of Iron', None, 'D3D8'),
        'gameJourney':                                     ('Journey to the Center of the Earth', None, 'D3D8'),
        'GameLOTR3':                                       ('Lords of the Realm III', None, 'D3D8'),
        'GameRenegade':                                    ('Command & Conquer: Renegade', None, 'D3D8'),
        'gameSHSotSE':                                     ('Sherlock Holmes: Secret of the Silver Earring', None, 'D3D8'),
        'GameSL':                                          ('Still Life', None, 'D3D8'),
        'GameSpiderManSD':                                 ('Spider-Man: Shattered Dimensions', None, 'D3D9'),
        'GameSyberia2':                                    ('Syberia II', None, 'D3D8'),
        'GameTV':                                          ('The Void', None, 'D3D9'),
        'gameTWC':                                         ('The White Chamber', None, 'D3D8'),
        'Gaurodan':                                        (None, None, 'D3D9Ex'),
        'generals':                                        ('Command & Conquer: Generals', None, 'D3D8'),
        'GenshinImpact':                                   ('Genshin Impact', None, 'D3D11'),
        'ggdx':                                            ('Guilty Gear Isuka', None, 'D3D8'),
        'ggx2':                                            ('Guilty Gear X2 Reload', None, 'D3D8'),
        'GhostRecon':                                      ('Tom Clancy\'s Ghost Recon', None, 'D3D8'),
        'globalops':                                       ('Global Operations', None, 'D3D8'),
        'GoaT':                                            ('Ghost of a Tale', None, 'D3D11'),
        'Gothic3':                                         ('Gothic 3', None, 'D3D9'),
        'GreatEscape':                                     ('The Great Escape (2003)', None, 'D3D8'),
        'GreedFall':                                       ('GreedFall', None, 'D3D11'),
        'GRID':                                            ('Race Driver: Grid', None, 'D3D9'),
        'Grim Dawn':                                       (None, None, 'D3D9Ex'),
        'Grim Dawn_':                                      (None, None, 'D3D11'),
        'grimrock':                                        ('Legend of Grimrock', None, 'D3D9'),
        'grimrock2':                                       ('Legend of Grimrock 2', None, 'D3D9'),
        'GRIS':                                            ('Gris', None, 'D3D11'),
        'gta3':                                            ('Grand Theft Auto III', None, 'D3D8'),
        'GTAIV':                                           ('Grand Theft Auto IV', None, 'D3D9'),
        'gta-vc':                                          ('Grand Theft Auto: Vice City', None, 'D3D8'),
        'GuacSTCE':                                        ('Guacamelee! Super Turbo Championship Edition', None, 'D3D9'),
        'Guild3':                                          ('The Guild 3', None, 'D3D11'),
        'GuildII':                                         ('The Guild II: Renaissance', None, 'D3D9'),
        'Gun':                                             (None, None, 'D3D9'),
        'Gw2-64':                                          ('Guild Wars 2', None, 'D3D11'),
        'Gw':                                              ('Guild Wars', None, 'D3D9'),
        'H5_Game':                                         ('Heroes of Might and Magic V', None, 'D3D9'),
        'Hades':                                           (None, None, 'D3D11'),
        'HatinTimeGame':                                   ('A Hat in Time', None, 'D3D9'),
        'hde':                                             ('Hidden & Dangerous Deluxe', None, 'D3D8'),
        'HellbladeGame-Win64-Shipping':                    ('Hellblade: Senua\'s Sacrifice', None, 'D3D11'),
        'Hellish Quart':                                   (None, None, 'D3D11'), # Still in beta, should recapture later
        'Hgma':                                            ('Haegemonia: The Solon Heritage', None, 'D3D8'),
        'hitman2':                                         ('Hitman 2: Silent Assassin', None, 'D3D8'),
        'HitmanContracts':                                 ('Hitman: Contracts', None, 'D3D8'),
        'hl2':                                             ('Half-Life 2', None, 'D3D9Ex'),
        'hod3pc':                                          ('The House of the Dead III', None, 'D3D8'),
        'hollow_knight':                                   ('Hollow Knight', None, 'D3D11'),
        'HoverAce':                                        ('Hover Ace', None, 'D3D8'),
        'Hydorah':                                         (None, None, 'D3D8'),
        'IC':                                              ('Impossible Creatures', None, 'D3D8'),
        'igi2':                                            ('I.G.I.-2: Covert Strike', None, 'D3D8'),
        'il2fb':                                           ('IL-2 Sturmovik: 1946', None, 'D3D8'), # OpenGL to D3D8 wrapper
        'IMM':                                             ('Made Man', None, 'D3D9'),
        'indy':                                            ('Indiana Jones and the Emperor\'s Tomb', None, 'D3D8'),
        'Injustice':                                       ('Injustice: Gods Among Us', None, 'D3D9Ex'),
        'Inquisitor':                                      (None, None, 'D3D8'),
        'IronHarvest':                                     ('Iron Harvest', None, 'D3D11'),
        'IronStorm':                                       ('Iron Storm', None, 'D3D8'),
        'iw3sp':                                           ('Call of Duty 4: Modern Warfare', None, 'D3D9'),
        'JadeEmpire':                                      ('Jade Empire', None, 'D3D9'),
        'JoaR':                                            ('Journey of a Roach', None, 'D3D9'),
        'JustCause3':                                      ('Just Cause 3', None, 'D3D11'),
        'k2':                                              ('Kohan II: Kings of War', None, 'D3D9'),
        'kaneandlynch':                                    ('Kane & Lynch: Dead Men', None, 'D3D9'),
        'KBWotN':                                          ('King\'s Bounty: Warriors of the North', None, 'D3D9'),
        'kenshi_x64':                                      ('Kenshi', None, 'D3D11'),
        'KnightShift':                                     ('KnightShift', None, 'D3D8'),
        'koa':                                             ('Kingdoms of Amalur: Re-Reckoning', None, 'D3D11'),
        'kof13_win32_Release':                             ('The King of Fighters XIII', None, 'D3D9'),
        'LEGO DC Super-villains_DX11':                     ('Lego DC Super-Villains', None, 'D3D11'),
        'LEGOEMMET':                                       ('The Lego Movie Videogame', None, 'D3D9'),
        'LEGOSTARWARSSKYWALKERSAGA_DX11':                  ('Lego Star Wars: The Skywalker Saga', None, 'D3D11'),
        'left4dead':                                       ('Left 4 Dead', None, 'D3D9'),
        'left4dead2':                                      ('Left 4 Dead 2', None, 'D3D9'),
        'LetsRide':                                        ('Let\'s Ride! Silver Buckle Stables', None, 'D3D8'),
        'Lithtech':                                        ('No One Lives Forever 2: A Spy in H.A.R.M.\'s Way', None, 'D3D8'),
        'lol.launcher':                                    ('League of Legends', None, 'D3D9'),
        'LordsOfTheFallen':                                ('Lords of the Fallen', None, 'D3D11'),
        'Machinarium':                                     (None, None, 'D3D9'),
        'Majesty2':                                        ('Majesty 2: The Fantasy Kingdom Sim', None, 'D3D9'),
        'MajestyHD':                                       ('Majesty Gold HD', None, 'D3D9'),
        'ma':                                              ('Massive Assault', None, 'D3D8'),
        'MadMax':                                          ('Mad Max', None, 'D3D11'),
        'Manhunt2':                                        ('Manhunt 2', None, 'D3D9'),
        'MasterOfOrion':                                   ('Master of Orion (2016)', None, 'D3D9'),
        'MaxPayne2':                                       ('Max Payne 2: The Fall of Max Payne', None, 'D3D8'),
        'MaxPayne':                                        ('Max Payne', None, 'D3D8'),
        'MCC-Win64-Shipping':                              ('Halo: The Master Chief Collection', None, 'D3D11'),
        'MCity_d':                                         ('Motor City Online', None, 'D3D8'),
        'MirrorsEdge':                                     ('Mirror\'s Edge', None, 'D3D9'),
        'MMCoH_HD':                                        ('Might & Magic: Clash of Heroes - Definitive Edition', None, 'D3D11'),
        'Morrowind':                                       ('The Elder Scrolls III: Morrowind', None, 'D3D8'),
        'mos':                                             ('The Moment of Silence', None, 'D3D8'),
        'NecroVisioN':                                     (None, None, 'D3D9'),
        'NecroVisioN_':                                    (None, None, 'D3D10'),
        'NFSHP2':                                          ('Need for Speed: Hot Pursuit 2', None, 'D3D8'),
        'nomads':                                          ('Project Nomads', None, 'D3D8'),
        'Nosferatu':                                       ('Nosferatu: The Wrath of Malachi', None, 'D3D8'),
        'nwn2main':                                        ('Neverwinter Nights 2', None, 'D3D9'),
        'Oblivion':                                        ('The Elder Scrolls IV: Oblivion', None, 'D3D9'),
        'OC1.1':                                           ('Outcast 1.1', None, 'D3D9'),
        'oriDE':                                           ('Ori and the Blind Forest: Definitive Edition', None, 'D3D11'),
        'Palworld-Win64-Shipping':                         ('Palworld', None, 'D3D11'),
        'PANZERS':                                         ('Codename: Panzers - Phase One', None, 'D3D9'),
        'PANZERS_Phase_2':                                 ('Codename: Panzers - Phase Two', None, 'D3D9'),
        'Patrician4':                                      ('Patrician IV: Conquest by Trade', None, 'D3D9'),
        'patriots':                                        ('Rise of Nations', None, 'D3D8'),
        'pc_matador':                                      ('El Matador', None, 'D3D9'),
        'PH':                                              ('Pirate Hunter', None, 'D3D9'),
        'Pirates!':                                        ('Sid Meier\'s Pirates! (2004)', None, 'D3D9'),
        'Planet of Lana':                                  (None, None, 'D3D11'),
        'Planetbase':                                      (None, None, 'D3D11'),
        'Player':                                          ('Ballance', None, 'D3D8'),
        'pop2':                                            ('Prince of Persia: Warrior Within', None, 'D3D9'),
        'pop3':                                            ('Prince of Persia: The Two Thrones', None, 'D3D9'),
        'POP':                                             ('Prince of Persia: The Sands of Time', None, 'D3D9'),
        'PortRoyale3':                                     ('Port Royale 3: Pirates & Merchants', None, 'D3D8'),
        'Prince of Persia':                                ('Prince of Persia (2008)', None, 'D3D9'),
        'prism3d':                                         ('18 Wheels of Steel: Across America', None, 'D3D8'),
        'Psychonauts':                                     (None, None, 'D3D9'),
        'Pure Pinball 2.0 REDUX':                          ('Pure Pinball 2.0 Redux', None, 'D3D8'),
        'Raiden3':                                         ('Raiden III Digital Edition', None, 'D3D9'),
        'Rayman Origins':                                  (None, None, 'D3D9'),
        'rayne1':                                          ('BloodRayne: Terminal Cut', None, 'D3D8'), #D3D9 with d3d8to9
        'rayne2':                                          ('BloodRayne 2: Terminal Cut', None, 'D3D8'), #D3D9 with d3d8to9
        'RCCars':                                          ('RC Cars', None, 'D3D8'),
        're':                                              ('Restaurant Empire', None, 'D3D8'),
        're0hd':                                           ('Resident Evil Zero HD Remaster', None, 'D3D9'),
        'RedOrchestra':                                    ('Red Orchestra: Ostfront 41-45', None, 'D3D9'),
        'RebelGalaxyGOG':                                  ('Rebel Galaxy', None, 'D3D9'),
        'RebelGalaxyGOG_':                                 ('Rebel Galaxy', None, 'D3D11'),
        'Reckoning':                                       ('Kingdoms of Amalur: Reckoning', None, 'D3D9'),
        'rf2':                                             ('Red Faction II', None, 'D3D8'),
        'RF':                                              ('Red Faction', None, 'D3D8'),
        'Rings':                                           ('The Lord of the Rings: War of the Ring', None, 'D3D9'),
        'Risen':                                           (None, None, 'D3D9'),
        'Risen_':                                          ('Risen 2: Dark Waters', None, 'D3D9'),
        'Risen3':                                          ('Risen 3: Titan Lords', None, 'D3D9'),
        'RomeTW':                                          ('Rome: Total War', None, 'D3D8'),
        'ROTK':                                            ('The Lord of the Rings: The Return of the King', None, 'D3D8'),
        'ROTTR':                                           ('Rise of the Tomb Raider', None, 'D3D11'),
        'RT3':                                             ('Railroad Tycoon 3', None, 'D3D8'),
        'SamMax201':                                       ('Sam & Max: Beyond Time and Space', None, 'D3D8'),
        'SC2_x64':                                         ('StarCraft II', None, 'D3D9'),
        'Scrap':                                           ('Scrapland Remastered', None, 'D3D8'),
        'SEGA Rally':                                      ('Sega Rally Revo', None, 'D3D9'),
        'SF3ClientFinal':                                  ('SpellForce 3', None, 'D3D11'),
        'shadows':                                         ('Shadows: Awakening', None, 'D3D11'),
        'ShadowWarrior2':                                  ('Shadow Warrior 2', None, 'D3D11'),
        'SILENT HILL 4':                                   ('Silent Hill 4: The Room', None, 'D3D8'),
        'silverfall':                                      ('Silverfall', None, 'D3D9'),
        'SinEpisodes':                                     ('SiN Episodes: Emergence', None, 'D3D9'),
        'Singularity':                                     (None, None, 'D3D9'),
        'Sins of a Solar Empire Rebellion':                ('Sins of a Solar Empire: Rebellion', None, 'D3D9'),
        'SkyrimSE':                                        ('The Elder Scrolls V: Skyrim Special Edition', None, 'D3D11'),
        'SniperElite':                                     ('Sniper Elite', None, 'D3D8'),
        'sof3':                                            ('Soldier of Fortune: Payback', None, 'D3D9'),
        'Soldiers':                                        ('Soldiers: Heroes of World War II', None, 'D3D8'),
        'sonic2app':                                       ('Sonic Adventure 2', None, 'D3D9'), # With the SA2 Render Fix mod
        'Soulstorm':                                       ('Warhammer 40,000: Dawn of War: Soulstorm', None, 'D3D9'),
        'SpaceHulkGame-Win64-Shipping':                    ('Space Hulk: Deathwing', None, 'D3D11'),
        'SpaceMarine':                                     ('Warhammer 40,000: Space Marine', None, 'D3D9'),
        'SPEED2':                                          ('Need for Speed: Underground 2', None, 'D3D9'),
        'SpellForce':                                      ('SpellForce - Platinum Edition', None, 'D3D9'),
        'SpellForce2':                                     ('SpellForce 2: Shadow Wars', None, 'D3D9'),
        'sr2':                                             ('Legacy of Kain: Soul Reaver 2', None, 'D3D8'),
        'SRS':                                             ('Street Racing Syndicate', None, 'D3D9'),
        'stdrt_':                                          ('Castlevania: The Lecarde Chronicles 2', 'https://castlevaniafan.fandom.com/wiki/Castlevania:_The_Lecarde_Chronicles', 'D3D9'),
        'stdrt':                                           ('Castlevania: The Lecarde Chronicles', 'https://castlevaniafan.fandom.com/wiki/Castlevania:_The_Lecarde_Chronicles', 'D3D9'),
        'StreetFighterV':                                  ('Street Fighter V', None, 'D3D11'),
        'SUDEKI':                                          ('Sudeki', None, 'D3D9'),
        'SuperMeatBoy':                                    ('Super Meat Boy', None, 'D3D9'),
        'SupremeCommander':                                ('Supreme Commander', None, 'D3D9'),
        'SupremeCommander_':                               ('Supreme Commander: Forged Alliance', None, 'D3D9'),
        'SupremeCommander2':                               ('Supreme Commander 2', None, 'D3D9'),
        'SupremeRuler2020GC':                              ('Supreme Ruler 2020', None, 'D3D8'),
        'SupremeRuler':                                    ('Supreme Ruler 2010', None, 'D3D9'),
        'sw':                                              ('Shadow Warrior (2013)', None, 'D3D9'),
        'sw.x64':                                          ('Shadow Warrior (2013)', None, 'D3D11'),
        'Swat4':                                           ('SWAT 4', None, 'D3D9'),
        'sweaw':                                           ('Star Wars: Empire at War', None, 'D3D9'),
        'T3Main':                                          ('Thief: Deadly Shadows', None, 'D3D8'),
        'TESV':                                            ('The Elder Scrolls V: Skyrim', None, 'D3D9'),
        'Texas HoldEm':                                    ('Telltale Texas Hold \'Em', None, 'D3D8'),
        'TFT':                                             ('The First Templar', None, 'D3D9'),
        'the last tinker':                                 ('The Last Tinker: City of Colors', None, 'D3D9'),
        'TheIOfTheDragon':                                 ('The I of the Dragon', None, 'D3D8'),
        'theHunter':                                       ('The Hunter', None, 'D3D9'),
        'TheSpiritAndTheMouse':                            ('The Spirit and the Mouse', None, 'D3D11'),
        'TimeShift':                                       (None, None, 'D3D9'),
        'ToEEa':                                           ('The Temple of Elemental Evil', None, 'D3D8'),
        'TopSpin':                                         ('Top Spin', None, 'D3D8'),
        'Torchlight':                                      (None, None, 'D3D9'),
        'tra':                                             ('Tomb Raider: Anniversary', None, 'D3D9'),
        'trl':                                             ('Tomb Raider: Legend', None, 'D3D9'),
        'tru':                                             ('Tomb Raider: Underworld', None, 'D3D9'),
        'Troy':                                            ('A Total War Saga: Troy', None, 'D3D11'),
        'Tunic':                                           (None, None, 'D3D11'),
        'Underspace':                                      (None, None, 'D3D11'),
        'Vampire':                                         ('Vampire: The Masquerade - Bloodlines', None, 'D3D9'),
        'VampireSurvivors':                                ('Vampire Survivors', None, 'D3D11'),
        'vermintide2':                                     ('Warhammer: Vermintide 2', None, 'D3D11'),
        'vietcong':                                        ('Vietcong', None, 'D3D9'),
        'W40k':                                            ('Warhammer 40,000: Dawn of War', None, 'D3D9'),
        'war3':                                            ('Warcraft III: Reign of Chaos', None, 'D3D8'),
        'WarChess':                                        ('War Chess', None, 'D3D8'),
        'Warrior_Kings_Battles':                           ('Warrior Kings: Battles', None, 'D3D8'),
        'warrior_kings':                                   ('Warrior Kings', None, 'D3D8'),
        'WA':                                              ('Worms Armageddon', None, 'D3D9'),
        'wic':                                             ('World in Conflict', None, 'D3D9'),
        'witcher2':                                        ('The Witcher 2: Assassins of Kings', None, 'D3D9'),
        'witcher3':                                        ('The Witcher 3: Wild Hunt', None, 'D3D11'),
        'witcher':                                         ('The Witcher', None, 'D3D9'),
        'witness64_d3d11':                                 ('The Witness', None, 'D3D11'),
        'Wow':                                             ('World of Warcraft', None, 'D3D11'),
        'Wow_':                                            ('World of Warcraft', None, 'D3D9'), # 3.3.5a Warmane
        'Wreckfest_x64':                                   ('Wreckfest', None, 'D3D11'),
        'X2':                                              ('X2: The Threat', None, 'D3D8'),
        'XANADU':                                          ('Xanadu Next', None, 'D3D8'),
        'XComGame':                                        ('XCOM: Enemy Unknown', None, 'D3D9'),
        'Yakuza0':                                         ('Yakuza 0', None, 'D3D11'),
        'ys6_win':                                         ('Ys VI: The Ark of Napishtim', None, 'D3D8'),
        'ysf_win':                                         ('Ys: The Oath in Felghana', None, 'D3D8'),
        'z2':                                              ('Z: Steel Soldiers', None, 'D3D8'),
        'zapper':                                          ('Zapper: One Wicked Cricket', None, 'D3D8'),
        'ZombieShooter':                                   ('Zombie Shooter', None, 'D3D8'),
        'ZWEI2P':                                          ('Zwei: The Ilvard Insurrection', None, 'D3D8')
    }

    @classmethod
    def get(cls, trace_name):
        return cls.trace_application_names.get(trace_name, None)

