class TraceAppNames:
    trace_application_names = {
        'AN2': 'AquaNox 2: Revelation',
        'Anno1701AddOn': 'Anno 1701',
        'AoW3': 'Age of Wonders III',
        'APGame': 'Alpha Protocol',
        'Aqua': 'AquaNox',
        'defiance': 'Legacy of Kain: Defiance',
        'DOW2': 'Warhammer 40,000: Dawn of War II',
        'drakensang': 'Drakensang: The Dark Eye',
        'FEAR': 'F.E.A.R.',
        'FruitNinja': 'Fruit Ninja',
        'Gothic3': 'Gothic 3',
        'Grim Dawn': 'Grim Dawn',
        'hod3pc': 'The House of the Dead III',
        'IMM': 'Made Man',
        'pc_matador': 'El Matador',
        'rayne2': 'BloodRayne 2: Terminal Cut',
        'RT3': 'Railroad Tycoon 3',
        'Sins of a Solar Empire Rebellion': 'Sins of a Solar Empire: Rebellion',
        'sr2': 'Legacy of Kain: Soul Reaver 2',
        'TFT': 'The First Templar',
        'TheIOfTheDragon': 'The I of the Dragon',
        'TopSpin': 'Top Spin',
        'Torchlight': 'Torchlight',
        'vietcong': 'Vietcong',
        'W40k': 'Warhammer 40,000: Dawn of War',
        'witcher2': 'The Witcher 2: Assassins of Kings',
        'Scrap': 'Scrapland Remastered',
        'DungeonSiege2': 'Dungeon Siege II',
        'Dragonshard': 'Dungeons & Dragons: Dragonshard',
        'POP': 'Prince of Persia: The Sands of Time',
        'RF': 'Red Faction',
        'SupremeCommander': 'Supreme Commander',
        'witcher': 'The Witcher',
        'warrior_kings': 'Warrior Kings',
        'Demonstone': 'Forgotten Realms: Demon Stone',
        'dreamfall': 'Dreamfall: The Longest Journey',
        'hde': 'Hidden & Dangerous Deluxe',
        'freelancer': 'Freelancer',
        'gta3': 'Grand Theft Auto III',
        'gta-vc': 'Grand Theft Auto: Vice City',
        'k2': 'Kohan II: Kings of War',
        'MaxPayne': 'Max Payne',
        'MaxPayne2': 'Max Payne 2: The Fall of Max Payne',
        'SPEED2': 'Need for Speed: Underground 2',
        'Lithtech': 'No One Lives Forever 2: A Spy in H.A.R.M.\'s Way',
        'war3': 'Warcraft III: Reign of Chaos',
        'generals': 'Command & Conquer: Generals',
        'hitman2': 'Hitman 2: Silent Assassin',
        'HitmanContracts': 'Hitman: Contracts',
        'EE2X': 'Empire Earth II',
        'EE3': 'Empire Earth III',
        'bo2': 'Legacy of Kain: Blood Omen 2',
        'GRID': 'Race Driver: Grid',
        'Oblivion': 'The Elder Scrolls IV: Oblivion',
        'Morrowind': 'The Elder Scrolls III: Morrowind',
        'Nosferatu': 'Nosferatu: The Wrath of Malachi',
        'JadeEmpire': 'Jade Empire',
        'ActOfWar_HighTreason': 'Act of War: High Treason',
        'Castlestrike': 'Castle Strike',
        'nomads': 'Project Nomads',
        'ROTK': 'The Lord of the Rings: The Return of the King',
        'flatout': 'FlatOut',
        'FlatOut2': 'FlatOut 2',
        'Gun': 'Gun',
        'IC': 'Impossible Creatures',
        'JoaR': 'Journey of a Roach',
        'Majesty2': 'Majesty 2: The Fantasy Kingdom Sim',
        'Swat4': 'SWAT 4',
        'ToEEa': 'The Temple of Elemental Evil',
        'Vampire': 'Vampire: The Masquerade - Bloodlines',
        'ColdWarAssault': 'Arma: Cold War Assault',
        'Curse': 'Curse: The Eye of Isis',
        'Enclave': 'Enclave',
        'igi2': 'I.G.I.-2: Covert Strike',
        'Inquisitor': 'Inquisitor',
        'Dredd': 'Judge Dredd: Dredd vs. Death',
        'nwn2main': 'Neverwinter Nights 2',
        'GTAIV': 'Grand Theft Auto IV',
        'FalloutNV': 'Fallout: New Vegas',
        'KBWotN': 'King\'s Bounty: Warriors of the North',
        'Injustice': 'Injustice: Gods Among Us',
        'SEGA Rally': 'Sega Rally Revo',
        'TimeShift': 'TimeShift',
        'SC2_x64': 'StarCraft II',
        'dragonnest': 'Dragon Nest',
        'Gw': 'Guild Wars',
        're0hd': 'Resident Evil Zero HD Remaster',
        'eqgame': 'EverQuest',
        'BGE': 'Beyond Good & Evil',
        'rayne1': 'BloodRayne: Terminal Cut',
        'Civ4Warlords': 'Sid Meier\'s Civilization IV',
        'PANZERS': 'Codename: Panzers - Phase One',
        'DX2Main': 'Deus Ex: Invisible War',
        'H5_Game': 'Heroes of Might and Magic V',
        'MirrorsEdge': 'Mirror\'s Edge',
        'T3Main': 'Thief: Deadly Shadows'
    }

    @classmethod
    def get(cls, trace_name):
        return cls.trace_application_names.get(trace_name, None)

