class TraceAppNames:
    trace_application_names = {
        'AbandonShip':                                     ('Abandon Ship', None, 'D3D11'),
        'ActOfWar':                                        ('Act of War: Direct Action', None, 'D3D9'),
        'ActOfWar_HighTreason':                            ('Act of War: High Treason', None, 'D3D9'),
        'AER':                                             ('Aer: Memories of Old', None, 'D3D11'),
        'AI':                                              ('Alien: Isolation', None, 'D3D11'),
        'AIMII':                                           ('A.I.M. 2: Clan Wars', None, 'D3D8'),
        'AIMRace':                                         ('A.I.M. Racing', None, 'D3D8'),
        'Against the Storm':                               (None, None, 'D3D11'),
        'alan_wakes_american_nightmare':                   ('Alan Wake\'s American Nightmare', None, 'D3D9'),
        'alanwake':                                        ('Alan Wake', None, 'D3D9'),
        'Alba':                                            ('Alba: A Wildlife Adventure', None, 'D3D11'),
        'Alcatraz':                                        ('1954 Alcatraz', None, 'D3D9'),
        'AlienShooter':                                    ('Alien Shooter', None, 'D3D8'),
        'AN2':                                             ('AquaNox 2: Revelation', None, 'D3D9'),
        'Anno1701AddOn':                                   ('Anno 1701', None, 'D3D9'),
        'Anno4':                                           ('Anno 1404', None, 'D3D9'),
        'Anno4_':                                          ('Anno 1404', None, 'D3D10'),
        'Another World':                                   (None, None, 'D3D8'),
        'AoW3':                                            ('Age of Wonders III', None, 'D3D9'),
        'APGame':                                          ('Alpha Protocol', None, 'D3D9'),
        'APlagueTaleInnocence_x64':                        ('A Plague Tale: Innocence', None, 'D3D11'),
        'Aqua':                                            ('AquaNox', None, 'D3D8'),
        'arma':                                            ('Arma: Armed Assault', None, 'D3D9'),
        'arma2':                                           ('Arma 2', None, 'D3D9Ex'),
        'arma2OA':                                         ('Arma 2: Operation Arrowhead', None, 'D3D9Ex'),
        'Arma3_x64':                                       ('Arma 3', None, 'D3D11'),
        'Armada2':                                         ('Star Trek: Armada II', None, 'D3D8'),
        'AshesEscalation_DX11':                            ('Ashes of the Singularity: Escalation', None, 'D3D11'),
        'AssassinsCreed_Dx9':                              ('Assassin\'s Creed', None, 'D3D9'),
        'AssassinsCreed_Dx10':                             ('Assassin\'s Creed', None, 'D3D10'),
        'ATThrone':                                        ('Ascension to the Throne', None, 'D3D9'),
        'AvenColony-Win64-Shipping':                       ('Aven Colony', None, 'D3D11'),
        'AVGame-Win64-Shipping':                           ('Vampyr', None, 'D3D11'),
        'AvP_Classic':                                     ('Aliens vs. Predator (2010)', None, 'D3D9'),
        'BatmanAC':                                        ('Batman: Arkham City', None, 'D3D9'),
        'BatmanAC_':                                       ('Batman: Arkham City', None, 'D3D11'),
        'BatmanAK':                                        ('Batman: Arkham Knight', None, 'D3D11'),
        'BatmanOrigins':                                   ('Batman: Arkham Origins', None, 'D3D11'),
        'BatmanOrigins_':                                  ('Batman: Arkham Origins', None, 'D3D9'),
        'BattleFleetGothic-Win64-Shipping':                ('Battlefleet Gothic: Armada', None, 'D3D11'),
        'BattlefleetGothic2-Win64-Shipping':               ('Battlefleet Gothic: Armada 2', None, 'D3D11'),
        'BattlefrontII':                                   ('Star Wars: Battlefront II', None, 'D3D9'),
        'Battlefront':                                     ('Star Wars: Battlefront', None, 'D3D9'),
        'battlezone2':                                     ('Battlezone: Combat Commander', None, 'D3D11'),
        'BBCT':                                            ('BlazBlue: Calamity Trigger', None, 'D3D9'),
        'BC':                                              ('Battle Chasers: Nightwar', None, 'D3D11'),
        'BC_':                                             ('Battle Chasers: Nightwar', None, 'D3D9'),
        'BEA':                                             ('Battle Engine Aquila', None, 'D3D9'),
        'Betrayer':                                        (None, None, 'D3D9'),
        'bg3_dx11':                                        ('Baldur\'s Gate 3', None, 'D3D11'),
        'BGE':                                             ('Beyond Good & Evil', None, 'D3D9'),
        'Biomutant-Win64-Shipping':                        ('Biomutant', None, 'D3D11'),
        'Bioshock':                                        ('BioShock', None, 'D3D9'),
        'Bioshock_':                                       ('BioShock', None, 'D3D10'),
        'Bioshock2':                                       ('BioShock 2', None, 'D3D9'),
        'Bioshock2_':                                      ('BioShock 2', None, 'D3D10'),
        'BioShockInfinite':                                ('BioShock Infinite', None, 'D3D11'),
        'Blacksad':                                        ('Blacksad: Under the Skin', None, 'D3D11'),
        'Bloodshed':                                       (None, None, 'D3D11'),
        'Blowout':                                         ('BlowOut', None, 'D3D8'),
        'BLUE PRINCE':                                     ('Blue Prince', None, 'D3D11'),
        'bms':                                             ('Black Mesa', None, 'D3D9Ex'),
        'bo2':                                             ('Legacy of Kain: Blood Omen 2', None, 'D3D8'),
        'Boltgun-Win64-Shipping':                          ('Warhammer 40,000: Boltgun', None, 'D3D11'),
        'Bombshell':                                       (None, None, 'D3D9'),
        'Bombshell_':                                      (None, None, 'D3D11'),
        'Borderlands2':                                    ('Borderlands 2', None, 'D3D9'),
        'BoundByFlame':                                    ('Bound by Flame', None, 'D3D9'),
        'braid64_d3d11_final':                             ('Braid Anniversary Edition', None, 'D3D11'),
        'Brawls':                                          ('Lego Brawls', None, 'D3D11'),
        'Brothers':                                        ('Brothers: A Tale of Two Sons', None, 'D3D9'),
        'BrutalLegend':                                    ('Brutal Legend', None, 'D3D9'),
        'BSTSD':                                           ('Broken Sword 3: The Sleeping Dragon', None, 'D3D8'),
        'Butcher':                                         (None, None, 'D3D11'),
        'Carmageddon_Max_Damage':                          ('Carmageddon: Max Damage', None, 'D3D11'),
        'Castlestrike':                                    ('Castle Strike', None, 'D3D8'),
        'Cave':                                            ('The Cave', None, 'D3D9'),
        'CCE':                                             ('Close Combat: Panthers in the Fog', None, 'D3D9'),
        'Chessmaster':                                     ('Chessmaster 9000', None, 'D3D8'),
        'Cinders':                                         (None, None, 'D3D11'),
        'Civ4Warlords':                                    ('Sid Meier\'s Civilization IV', None, 'D3D9'),
        'CivCity Rome':                                    ('CivCity: Rome', None, 'D3D9'),
        'ClientG':                                         ('Conan Unconquered', None, 'D3D11'),
        'Cloudpunk':                                       (None, None, 'D3D11'),
        'CNC3EP1':                                         ('Command & Conquer 3: Tiberium Wars', None, 'D3D9'),
        'CoD2SP_s':                                        ('Call of Duty 2', None, 'D3D9'),
        'CoDWaW':                                          ('Call of Duty: World at War', None, 'D3D9'),
        'CoJ':                                             ('Call of Juarez', None, 'D3D9'),
        'CoJ_DX10':                                        ('Call of Juarez', None, 'D3D10'),
        'CoJGunslinger':                                   ('Call of Juarez: Gunslinger', None, 'D3D9'),
        'ColdWarAssault':                                  ('Arma: Cold War Assault', None, 'D3D8'),
        'Commandos3':                                      ('Commandos 3: Destination Berlin', None, 'D3D8'),
        'consortium':                                      ('Consortium', None, 'D3D9Ex'), # Master Edition
        'Control_DX11':                                    ('Control', None, 'D3D11'),
        'CostumeQuest2':                                   ('Costume Quest 2', None, 'D3D11'),
        'Cq':                                              ('Costume Quest', None, 'D3D9'),
        'Crysis':                                          (None, None, 'D3D9'),
        'Crysis_':                                         (None, None, 'D3D10'),
        'cs2':                                             ('Counter-Strike 2', None, 'D3D11'),
        'CT3':                                             ('Crazy Taxi 3: High Roller', None, 'D3D9'),
        'Cuphead':                                         (None, None, 'D3D11'),
        'Curse':                                           ('Curse: The Eye of Isis', None, 'D3D8'),
        'Dagon':                                           ('Dagon: by H. P. Lovecraft', None, 'D3D11'),
        'dangerouswaters':                                 ('Dangerous Waters', None, 'D3D8'),
        'DAOrigins':                                       ('Dragon Age: Origins', None, 'D3D9'),
        'DarkFallLostSouls':                               ('Dark Fall 3: Lost Souls', None, 'D3D9'),
        'Darksiders2':                                     ('Darksiders II: Deathinitive Edition', None, 'D3D9'),
        'dawnofmagic2':                                    ('Dawn of Magic 2', None, 'D3D9'),
        'Daymare_MASTER-Win64-Shipping':                   ('Daymare: 1998', None, 'D3D11'),
        'DCS':                                             ('DCS World', None, 'D3D11'),
        'DDDA':                                            ('Dragon\'s Dogma: Dark Arisen', None, 'D3D9'),
        'Dead Space':                                      (None, None, 'D3D9'),
        'deadlock':                                        ('Deadlock', None, 'D3D11'),
        'Death and Taxes':                                 (None, None, 'D3D11'),
        'defiance':                                        ('Legacy of Kain: Defiance', None, 'D3D9'),
        'desolation':                                      ('Beautiful Desolation', None, 'D3D11'),
        'Demonstone':                                      ('Forgotten Realms: Demon Stone', None, 'D3D9'),
        'DesertsOfKharak':                                 ('Homeworld: Deserts of Kharak', None, 'D3D11'),
        'DesertStorm':                                     ('Conflict: Desert Storm', None, 'D3D8'),
        'Dishonored':                                      (None, None, 'D3D9'),
        'div':                                             ('Beyond Divinity', None, 'D3D9'),
        'Divinity2':                                       ('Divinity II: Developer\'s Cut', None, 'D3D9'),
        'dontstarve':                                      ('Don\'t Starve', None, 'D3D9Ex'),
        'DOW2':                                            ('Warhammer 40,000: Dawn of War II', None, 'D3D9'),
        'DragonAgeInquisition':                            ('Dragon Age: Inquisition', None, 'D3D11'),
        'dragonnest':                                      ('Dragon Nest', None, 'D3D9'),
        'DragonCommander':                                 ('Divinity: Dragon Commander', None, 'D3D9'),
        'Dragonshard':                                     ('Dungeons & Dragons: Dragonshard', None, 'D3D9'),
        'Drake':                                           ('Drake of the 99 Dragons', None, 'D3D8'),
        'drakensang':                                      ('Drakensang: The Dark Eye', None, 'D3D9'),
        'dreamfall':                                       ('Dreamfall: The Longest Journey', None, 'D3D9'),
        'Dredd':                                           ('Judge Dredd: Dredd vs. Death', None, 'D3D8'),
        'Driftland-Win64-Shipping':                        ('Driftland: The Magic Revival', None, 'D3D11'),
        'DukeForever':                                     ('Duke Nukem Forever: Restoration Project', None, 'D3D8'),
        'DungeonSiege2':                                   ('Dungeon Siege II', None, 'D3D9'),
        'Dungeon Siege III':                               (None, None, 'D3D9'),
        'Dungeons2':                                       ('Dungeons 2', None, 'D3D11'),
        'Dungeons2_':                                      ('Dungeons 2', None, 'D3D9'),
        'Dwarves':                                         ('The Dwarves', None, 'D3D11'),
        'DX2Main':                                         ('Deus Ex: Invisible War', None, 'D3D8'),
        'DXHRDC':                                          ('Deus Ex: Human Revolution - Director\'s Cut', None, 'D3D11'),
        'DyingLightGame':                                  ('Dying Light', None, 'D3D11'),
        'E5':                                              ('Brigade E5: New Jagged Union', None, 'D3D8'),
        'E6':                                              ('7.62 High Calibre', None, 'D3D9'),
        'ed6_win':                                         ('The Legend of Heroes: Trails in the Sky', None, 'D3D8'),
        'Eden':                                            ('Project Eden', None, 'D3D8'),
        'EE2X':                                            ('Empire Earth II', None, 'D3D8'),
        'EE3':                                             ('Empire Earth III', None, 'D3D9'),
        'ElvenLegacy':                                     ('Elven Legacy', None, 'D3D9'),
        'Ember':                                           (None, None, 'D3D9'),
        'Empires_DMW':                                     ('Empires: Dawn of the Modern World', None, 'D3D8'),
        'Encased':                                         (None, None, 'D3D11'),
        'Enclave':                                         (None, None, 'D3D8'),
        'Endless space':                                   ('Endless Space', None, 'D3D9'),
        'engine':                                          ('Cossacks II: Battle for Europe', None, 'D3D8'),
        'engine_':                                         ('Alexander', None, 'D3D8'),
        'EoCApp':                                          ('Divinity: Original Sin', None, 'D3D9'),
        'EoCApp_':                                         ('Divinity: Original Sin - Enhanced Edition', None, 'D3D11'),
        'EoCApp__':                                        ('Divinity: Original Sin II', None, 'D3D11'),
        'EoCApp___':                                       ('Divinity: Original Sin II - Definitive Edition', None, 'D3D11'),
        'EotU-Win64-Shipping':                             ('Empires of the Undergrowth', None, 'D3D11'),
        'eqgame':                                          ('EverQuest', None, 'D3D9'),
        'eqgame_':                                         ('EverQuest', None, 'D3D11'),
        'ES2-Win64-Shipping':                              ('Everspace 2', None, 'D3D11'),
        'eso64':                                           ('The Elder Scrolls Online', None, 'D3D11'),
        'eu3game':                                         ('Europa Universalis III', None, 'D3D9'),
        'Europa1400Gold_TL':                               ('Europa 1400: The Guild', None, 'D3D8'),
        'EvilGeniusExeStub-Release':                       ('Evil Genius', None, 'D3D9'),
        'EYE':                                             ('E.Y.E: Divine Cybermancy', None, 'D3D9'),
        'EXAPUNKS':                                        ('Exapunks', None, 'D3D11'),
        'extremetrucker':                                  ('18 Wheels of Steel: Extreme Trucker 2', None, 'D3D9Ex'),
        'Fallout3':                                        ('Fallout 3', None, 'D3D9'),
        'Fallout4':                                        ('Fallout 4', None, 'D3D11'),
        'FalloutNV':                                       ('Fallout: New Vegas', None, 'D3D9'),
        'FantasyMapSimulator':                             ('Fantasy Map Simulator', None, 'D3D11'), # No PCGW page yet
        'FarCry':                                          ('Far Cry', None, 'D3D9'),
        'farcry2':                                         ('Far Cry 2', None, 'D3D9'),
        'FarCryNewDawn':                                   ('Far Cry New Dawn', None, 'D3D11'),
        'facesofwar':                                      ('Faces of War', None, 'D3D9'),
        'fate':                                            ('FATE', None, 'D3D8'),
        'Fate':                                            ('FATE: The Cursed King', None, 'D3D8'),
        'Fate_':                                           ('FATE: The Traitor Soul', None, 'D3D8'),
        'Fate__':                                          ('FATE: Undiscovered Realms', None, 'D3D8'),
        'F.E.A.R. 3':                                      (None, None, 'D3D11'),
        'F.E.A.R. 3_':                                     (None, None, 'D3D9'),
        'FEAR':                                            ('F.E.A.R.', None, 'D3D9'),
        'FEAR2':                                           ('F.E.A.R. 2: Project Origin', None, 'D3D9'),
        'fforce':                                          ('Freedom Force', None, 'D3D8'),
        'ffvt3r':                                          ('Freedom Force vs. The 3rd Reich', None, 'D3D9'),
        'fifa2003':                                        ('FIFA Football 2003', None, 'D3D8'),
        'FLASHOUT2':                                       ('Flashout 2', None, 'D3D9'),
        'FlatOut2':                                        ('FlatOut 2', None, 'D3D9'),
        'flatout':                                         ('FlatOut', None, 'D3D9'),
        'forces':                                          ('Incoming Forces', None, 'D3D8'),
        'Freedom':                                         ('Freedom Fighters', None, 'D3D9'),
        'freelancer':                                      ('Freelancer', None, 'D3D8'),
        'Frostpunk':                                       (None, None, 'D3D11'),
        'Frozenheim-Win64-Shipping':                       ('Frozenheim', None, 'D3D11'),
        'FruitNinja':                                      ('Fruit Ninja', None, 'D3D9'),
        'fsasgame':                                        ('Lost Horizon', None, 'D3D9'),
        'FSD-Win64-Shipping':                              ('Deep Rock Galactic', None, 'D3D11'),
        'fw':                                              ('Fantasy Wars', None, 'D3D9'),
        'Galak-Z':                                         ('Galak-Z: The Dimensional', None, 'D3D9'),
        'GalCiv2':                                         ('Galactic Civilizations II', None, 'D3D9'),
        'game18WSET':                                      ('18 Wheels of Steel: Extreme Trucker', None, 'D3D9Ex'),
        'gameBFME':                                        ('The Lord of the Rings: The Battle for Middle-earth', None, 'D3D9'),
        'GameBlitzkrieg':                                  ('Blitzkrieg', None, 'D3D8'),
        'GameDesertLaw':                                   ('Desert Law', None, 'D3D8'),
        'GameHaegemonia':                                  ('Haegemonia: Legions of Iron', None, 'D3D8'),
        'gameJourney':                                     ('Journey to the Center of the Earth', None, 'D3D8'),
        'GameLOTR3':                                       ('Lords of the Realm III', None, 'D3D8'),
        'GameRenegade':                                    ('Command & Conquer: Renegade', None, 'D3D8'),
        'gameSHJTR':                                       ('Sherlock Holmes versus Jack the Ripper', None, 'D3D9'),
        'gameSHSotSE':                                     ('Sherlock Holmes: Secret of the Silver Earring', None, 'D3D8'),
        'gameSHTA':                                        ('Sherlock Holmes: The Awakened - Remastered', None, 'D3D9'),
        'GameSL':                                          ('Still Life', None, 'D3D8'),
        'GameSpiderManSD':                                 ('Spider-Man: Shattered Dimensions', None, 'D3D9'),
        'GameSyberia2':                                    ('Syberia II', None, 'D3D8'),
        'gameTTSH':                                        ('The Testament of Sherlock Holmes', None, 'D3D9'),
        'GameTV':                                          ('The Void', None, 'D3D9'),
        'gameTWC':                                         ('The White Chamber', None, 'D3D8'),
        'Gaurodan':                                        (None, None, 'D3D9Ex'),
        'generals':                                        ('Command & Conquer: Generals', None, 'D3D8'),
        'GenshinImpact':                                   ('Genshin Impact', None, 'D3D11'),
        'ggdx':                                            ('Guilty Gear Isuka', None, 'D3D8'),
        'ggx2':                                            ('Guilty Gear X2 Reload', None, 'D3D8'),
        'GhostRecon':                                      ('Tom Clancy\'s Ghost Recon', None, 'D3D8'),
        'globalops':                                       ('Global Operations', None, 'D3D8'),
        'GoaT':                                            ('Ghost of a Tale', None, 'D3D11'),
        'Gothic3':                                         ('Gothic 3', None, 'D3D9'),
        'GoW':                                             ('God of War', None, 'D3D11'),
        'GreatEscape':                                     ('The Great Escape (2003)', None, 'D3D8'),
        'GreedFall':                                       ('GreedFall', None, 'D3D11'),
        'GRID':                                            ('Race Driver: Grid', None, 'D3D9'),
        'Grim Dawn':                                       (None, None, 'D3D9Ex'),
        'Grim Dawn_':                                      (None, None, 'D3D11'),
        'grimrock':                                        ('Legend of Grimrock', None, 'D3D9'),
        'grimrock2':                                       ('Legend of Grimrock 2', None, 'D3D9'),
        'Grip-Win64-Shipping':                             ('GRIP: Combat Racing', None, 'D3D11'),
        'GRIS':                                            ('Gris', None, 'D3D11'),
        'gta3':                                            ('Grand Theft Auto III', None, 'D3D8'),
        'GTA5':                                            ('Grand Theft Auto V', None, 'D3D11'),
        'GTAIV':                                           ('Grand Theft Auto IV', None, 'D3D9'),
        'gta-vc':                                          ('Grand Theft Auto: Vice City', None, 'D3D8'),
        'GuacSTCE':                                        ('Guacamelee! Super Turbo Championship Edition', None, 'D3D9'),
        'Guild3':                                          ('The Guild 3', None, 'D3D11'),
        'GuildII':                                         ('The Guild II: Renaissance', None, 'D3D9'),
        'Gun':                                             (None, None, 'D3D9'),
        'Gunmetal':                                        ('Gun Metal', None, 'D3D9'),
        'Gw2-64':                                          ('Guild Wars 2', None, 'D3D11'),
        'Gw':                                              ('Guild Wars', None, 'D3D9'),
        'H5_Game':                                         ('Heroes of Might and Magic V', None, 'D3D9'),
        'Hades':                                           (None, None, 'D3D11'),
        'HatinTimeGame':                                   ('A Hat in Time', None, 'D3D9'),
        'HavenPark':                                       ('Haven Park', None, 'D3D11'),
        'hde':                                             ('Hidden & Dangerous Deluxe', None, 'D3D8'),
        'HeavyRain':                                       ('Heavy Rain', None, 'D3D11'),
        'HellbladeGame-Win64-Shipping':                    ('Hellblade: Senua\'s Sacrifice', None, 'D3D11'),
        'Helldorado':                                      (None, None, 'D3D9'),
        'Hellish Quart':                                   (None, None, 'D3D11'), # Still in beta, should recapture later
        'hg2':                                             ('Hotel Giant 2', None, 'D3D9'),
        'Hgma':                                            ('Haegemonia: The Solon Heritage', None, 'D3D8'),
        'hitman2':                                         ('Hitman 2: Silent Assassin', None, 'D3D8'),
        'HitmanBloodMoney':                                ('Hitman: Blood Money', None, 'D3D9'),
        'HitmanContracts':                                 ('Hitman: Contracts', None, 'D3D8'),
        'hl2':                                             ('Half-Life 2', None, 'D3D9Ex'),
        'HLA':                                             ('7.62 Hard Life', None, 'D3D9'),
        'HMA':                                             ('Hitman: Absolution', None, 'D3D11'),
        'hod3pc':                                          ('The House of the Dead III', None, 'D3D8'),
        'hoi3game':                                        ('Hearts of Iron III', None, 'D3D9'),
        'hollow_knight':                                   ('Hollow Knight', None, 'D3D11'),
        'hotel':                                           ('Hotel Giant', None, 'D3D9'),
        'HoverAce':                                        ('Hover Ace', None, 'D3D8'),
        'Hydorah':                                         (None, None, 'D3D8'),
        'IC':                                              ('Impossible Creatures', None, 'D3D8'),
        'igi2':                                            ('I.G.I.-2: Covert Strike', None, 'D3D8'),
        'il2fb':                                           ('IL-2 Sturmovik: 1946', None, 'D3D8'), # OpenGL to D3D8 wrapper
        'IMM':                                             ('Made Man', None, 'D3D9'),
        'ImperialGlory':                                   ('Imperial Glory', None, 'D3D9'),
        'indy':                                            ('Indiana Jones and the Emperor\'s Tomb', None, 'D3D8'),
        'Injustice':                                       ('Injustice: Gods Among Us', None, 'D3D9Ex'),
        'Inquisitor':                                      (None, None, 'D3D8'),
        'Iratus':                                          ('Iratus: Lord of the Dead', None, 'D3D11'),
        'IronHarvest':                                     ('Iron Harvest', None, 'D3D11'),
        'IronStorm':                                       ('Iron Storm', None, 'D3D8'),
        'iw3sp':                                           ('Call of Duty 4: Modern Warfare', None, 'D3D9'),
        'iw6sp64_ship':                                    ('Call of Duty: Ghosts', None, 'D3D11'),
        'JadeEmpire':                                      ('Jade Empire', None, 'D3D9'),
        'JoaR':                                            ('Journey of a Roach', None, 'D3D9'),
        'JustCause':                                       ('Just Cause', None, 'D3D9'),
        'JustCause3':                                      ('Just Cause 3', None, 'D3D11'),
        'k2':                                              ('Kohan II: Kings of War', None, 'D3D9'),
        'kaneandlynch':                                    ('Kane & Lynch: Dead Men', None, 'D3D9'),
        'KBWotN':                                          ('King\'s Bounty: Warriors of the North', None, 'D3D9'),
        'kenshi_x64':                                      ('Kenshi', None, 'D3D11'),
        'kl2':                                             ('Kane & Lynch 2: Dog Days', None, 'D3D9'),
        'KnightShift':                                     ('KnightShift', None, 'D3D8'),
        'koa':                                             ('Kingdoms of Amalur: Re-Reckoning', None, 'D3D11'),
        'kof13_win32_Release':                             ('The King of Fighters XIII', None, 'D3D9'),
        'LEGO DC Super-villains_DX11':                     ('Lego DC Super-Villains', None, 'D3D11'),
        'LEGOEMMET':                                       ('The Lego Movie Videogame', None, 'D3D9'),
        'LEGOSTARWARSSKYWALKERSAGA_DX11':                  ('Lego Star Wars: The Skywalker Saga', None, 'D3D11'),
        'left4dead':                                       ('Left 4 Dead', None, 'D3D9'),
        'left4dead2':                                      ('Left 4 Dead 2', None, 'D3D9'),
        'LetsRide':                                        ('Let\'s Ride! Silver Buckle Stables', None, 'D3D8'),
        'Lithtech':                                        ('No One Lives Forever 2: A Spy in H.A.R.M.\'s Way', None, 'D3D8'),
        'lol.launcher':                                    ('League of Legends', None, 'D3D9'),
        'LordsOfTheFallen':                                ('Lords of the Fallen', None, 'D3D11'),
        'LostEmber-Win64-Shipping':                        ('Lost Ember', None, 'D3D11'),
        'Machinarium':                                     (None, None, 'D3D9'),
        'mafia2':                                          ('Mafia II', None, 'D3D9'),
        'Mafia II Definitive Edition':                     ('Mafia II: Definitive Edition', None, 'D3D11'),
        'Majesty2':                                        ('Majesty 2: The Fantasy Kingdom Sim', None, 'D3D9'),
        'MajestyHD':                                       ('Majesty Gold HD', None, 'D3D9'),
        'ma':                                              ('Massive Assault', None, 'D3D8'),
        'Mable':                                           ('Mable and the Wood', None, 'D3D11'),
        'MadMax':                                          ('Mad Max', None, 'D3D11'),
        'Manhunt2':                                        ('Manhunt 2', None, 'D3D9'),
        'mapr':                                            ('Massive Assault: Phantom Renaissance', None, 'D3D8'),
        'MarsWarLogs':                                     ('Mars: War Logs', None, 'D3D9'),
        'MasterOfOrion':                                   ('Master of Orion (2016)', None, 'D3D9'),
        'MaxPayne2':                                       ('Max Payne 2: The Fall of Max Payne', None, 'D3D8'),
        'MaxPayne':                                        ('Max Payne', None, 'D3D8'),
        'mb_warband':                                      ('Mount & Blade: Warband', None, 'D3D9'),
        'MCC-Win64-Shipping':                              ('Halo: The Master Chief Collection', None, 'D3D11'),
        'MCity_d':                                         ('Motor City Online', None, 'D3D8'),
        'Mechajammer':                                     (None, None, 'D3D11'),
        'METAL GEAR RISING REVENGEANCE':                   ('Metal Gear Rising: Revengeance', None, 'D3D9'),
        'METAPHOR':                                        ('Metaphor: ReFantazio', None, 'D3D11'),
        'MetroExodus':                                     ('Metro Exodus', None, 'D3D11'),
        'MirrorsEdge':                                     ('Mirror\'s Edge', None, 'D3D9'),
        'MMCoH_HD':                                        ('Might & Magic: Clash of Heroes - Definitive Edition', None, 'D3D11'),
        'momo1_v151':                                      ('Momodora I', None, 'D3D8'),
        'momodora2':                                       ('Momodora II', None, 'D3D8'),
        'mordheim':                                        ('Mordheim: City of the Damned', None, 'D3D11'),
        'Morrowind':                                       ('The Elder Scrolls III: Morrowind', None, 'D3D8'),
        'mos':                                             ('The Moment of Silence', None, 'D3D8'),
        'mow':                                             ('Men of War', None, 'D3D9'),
        'mow_assault_squad':                               ('Men of War: Assault Squad', None, 'D3D9'),
        'Napoleon':                                        ('Napoleon: Total War', None, 'D3D9'),
        'Near-Mage':                                       (None, None, 'D3D11'),
        'NecroVisioN':                                     (None, None, 'D3D9'),
        'NecroVisioN_':                                    (None, None, 'D3D10'),
        'Never_Alone':                                     ('Never Alone', None, 'D3D9'),
        'nexus_DX9':                                       ('Nexus: The Jupiter Incident', None, 'D3D9'),
        'NFSHP2':                                          ('Need for Speed: Hot Pursuit 2', None, 'D3D8'),
        'Nikopol':                                         ('Nikopol: Secrets of the Immortals', None, 'D3D9'),
        'nomads':                                          ('Project Nomads', None, 'D3D8'),
        'Nosferatu':                                       ('Nosferatu: The Wrath of Malachi', None, 'D3D8'),
        'nwn2main':                                        ('Neverwinter Nights 2', None, 'D3D9'),
        'Oblivion':                                        ('The Elder Scrolls IV: Oblivion', None, 'D3D9'),
        'OC1.1':                                           ('Outcast 1.1', None, 'D3D9'),
        'ocd':                                             ('Overclocked: A History of Violence', None, 'D3D9'),
        'OfOrcsAndMen':                                    ('Of Orcs and Men', None, 'D3D9'),
        'oriDE':                                           ('Ori and the Blind Forest: Definitive Edition', None, 'D3D11'),
        'OriginClient':                                    ('Silkroad Online', 'https://www.joymax.com/silkroad/', 'D3D9'),
        'outthereomega':                                   ('Out There: Ω Edition', None, 'D3D11'),
        'Palworld-Win64-Shipping':                         ('Palworld', None, 'D3D11'),
        'PANZERS':                                         ('Codename: Panzers - Phase One', None, 'D3D9'),
        'PANZERS_Phase_2':                                 ('Codename: Panzers - Phase Two', None, 'D3D9'),
        'Passpartout':                                     ('Passpartout: The Starving Artist', None, 'D3D11'),
        'Patrician4':                                      ('Patrician IV: Conquest by Trade', None, 'D3D9'),
        'patriots':                                        ('Rise of Nations', None, 'D3D8'),
        'pc_matador':                                      ('El Matador', None, 'D3D9'),
        'PH':                                              ('Pirate Hunter', None, 'D3D9'),
        'pico_park':                                       ('Pico Park', None, 'D3D9'),
        'Pilgrims':                                        (None, None, 'D3D11'),
        'Pine':                                            (None, None, 'D3D11'),
        'Pirates!':                                        ('Sid Meier\'s Pirates! (2004)', None, 'D3D9'),
        'Planet of Lana':                                  (None, None, 'D3D11'),
        'Planetbase':                                      (None, None, 'D3D11'),
        'Player':                                          ('Ballance', None, 'D3D8'),
        'pop2':                                            ('Prince of Persia: Warrior Within', None, 'D3D9'),
        'pop3':                                            ('Prince of Persia: The Two Thrones', None, 'D3D9'),
        'POP':                                             ('Prince of Persia: The Sands of Time', None, 'D3D9'),
        'PortRoyale3':                                     ('Port Royale 3: Pirates & Merchants', None, 'D3D8'),
        'Postal':                                          (None, None, 'D3D9'),
        'Praest-Win64-Shipping':                           ('Graven', None, 'D3D11'),
        'Praetorians-Win64-Shipping':                      ('Praetorians HD Remaster', None, 'D3D11'),
        'Prey':                                            ('Prey (2017)', None, 'D3D11'),
        'Prince of Persia':                                ('Prince of Persia (2008)', None, 'D3D9'),
        'prism3d':                                         ('18 Wheels of Steel: Across America', None, 'D3D8'),
        'Project_C-Win64-Shipping':                        ('Apsulov: End of Gods', None, 'D3D11'),
        'Psychonauts':                                     (None, None, 'D3D9'),
        'Pure Pinball 2.0 REDUX':                          ('Pure Pinball 2.0 Redux', None, 'D3D8'),
        'QUBEGame':                                        ('Q.U.B.E.: Director\'s Cut', None, 'D3D9'),
        'Raiden3':                                         ('Raiden III Digital Edition', None, 'D3D9'),
        'Rayman Origins':                                  (None, None, 'D3D9'),
        'rayne1':                                          ('BloodRayne: Terminal Cut', None, 'D3D8'), #D3D9 with d3d8to9
        'rayne2':                                          ('BloodRayne 2: Terminal Cut', None, 'D3D8'), #D3D9 with d3d8to9
        'RCCars':                                          ('RC Cars', None, 'D3D8'),
        're':                                              ('Restaurant Empire', None, 'D3D8'),
        'Re-Legion':                                       (None, None, 'D3D11'),
        're0hd':                                           ('Resident Evil Zero HD Remaster', None, 'D3D9'),
        'RedOrchestra':                                    ('Red Orchestra: Ostfront 41-45', None, 'D3D9'),
        'redtide':                                         ('Men of War: Red Tide', None, 'D3D9'),
        'RebelGalaxyGOG':                                  ('Rebel Galaxy', None, 'D3D9'),
        'RebelGalaxyGOG_':                                 ('Rebel Galaxy', None, 'D3D11'),
        'Reckoning':                                       ('Kingdoms of Amalur: Reckoning', None, 'D3D9'),
        'RememberMe':                                      ('Remember Me', None, 'D3D9'),
        'rf2':                                             ('Red Faction II', None, 'D3D8'),
        'RF':                                              ('Red Faction', None, 'D3D8'),
        'Rings':                                           ('The Lord of the Rings: War of the Ring', None, 'D3D9'),
        'Risen':                                           (None, None, 'D3D9'),
        'Risen_':                                          ('Risen 2: Dark Waters', None, 'D3D9'),
        'Risen3':                                          ('Risen 3: Titan Lords', None, 'D3D9'),
        'RogueTrooper':                                    ('Rogue Trooper', None, 'D3D9'),
        'RomeGame':                                        ('Europa Universalis: Rome', None, 'D3D9'),
        'RomeTW':                                          ('Rome: Total War', None, 'D3D8'),
        'ROTK':                                            ('The Lord of the Rings: The Return of the King', None, 'D3D8'),
        'ROTT':                                            ('Rise of the Triad', None, 'D3D9'),
        'ROTTR':                                           ('Rise of the Tomb Raider', None, 'D3D11'),
        'RT3':                                             ('Railroad Tycoon 3', None, 'D3D8'),
        'RTR_x64':                                         ('Rogue Trooper Redux', None, 'D3D11'),
        'SaintsRowTheThird':                               ('Saints Row: The Third', None, 'D3D9Ex'),
        'SaintsRowTheThird_DX11':                          ('Saints Row: The Third', None, 'D3D11'),
        'SamMax201':                                       ('Sam & Max: Beyond Time and Space', None, 'D3D8'),
        'SC2_x64':                                         ('StarCraft II', None, 'D3D9'),
        'Scrap':                                           ('Scrapland Remastered', None, 'D3D8'),
        'SEGA Rally':                                      ('Sega Rally Revo', None, 'D3D9'),
        'SensibleSoccer2006':                              ('Sensible Soccer 2006', None, 'D3D9'),
        'Seven-Win64-Shipping':                            ('Seven: The Days Long Gone', None, 'D3D11'),
        'sdhdship':                                        ('Sleeping Dogs: Definitive Edition', None, 'D3D11'),
        'SF3ClientFinal':                                  ('SpellForce 3', None, 'D3D11'),
        'Shadow Tactics':                                  ('Shadow Tactics: Blades of the Shogun', None, 'D3D11'),
        'shadows':                                         ('Shadows: Awakening', None, 'D3D11'),
        'ShadowWarrior2':                                  ('Shadow Warrior 2', None, 'D3D11'),
        'Shank':                                           (None, None, 'D3D9'),
        'ShantaeHero':                                     ('Shantae: Half-Genie Hero', None, 'D3D9Ex'),
        'ShatteredTOTFK-Win64-Shipping':                   ('Shattered - Tale of the Forgotten King', None, 'D3D11'),
        'SherlockHolmes_TheHoundofTheBaskervilles':        ('Sherlock Holmes and the Hound of the Baskervilles', None, 'D3D9'),
        'ShippingPC-BmGame':                               ('Batman: Arkham Asylum', None, 'D3D9'),
        'sigma':                                           ('Sigma Theory: Global Cold War', None, 'D3D11'),
        'SILENT HILL 4':                                   ('Silent Hill 4: The Room', None, 'D3D8'),
        'silverfall':                                      ('Silverfall', None, 'D3D9'),
        'SineMoraEX':                                      ('Sine Mora EX', None, 'D3D9'),
        'SinEpisodes':                                     ('SiN Episodes: Emergence', None, 'D3D9'),
        'Singularity':                                     (None, None, 'D3D9'),
        'Sins of a Solar Empire':                          ('Sins of a Solar Empire', None, 'D3D9'),
        'Sins of a Solar Empire Rebellion':                ('Sins of a Solar Empire: Rebellion', None, 'D3D9'),
        'SkyrimSE':                                        ('The Elder Scrolls V: Skyrim Special Edition', None, 'D3D11'),
        'Smersh':                                          ('Death to Spies', None, 'D3D9'),
        'Sniper_x86':                                      ('Sniper: Ghost Warrior', None, 'D3D9'),
        'SniperElite':                                     ('Sniper Elite', None, 'D3D8'),
        'snowblind':                                       ('Project Snowblind', None, 'D3D9'),
        'sof3':                                            ('Soldier of Fortune: Payback', None, 'D3D9'),
        'SOG':                                             ('Elite Warriors: Vietnam', None, 'D3D9'),
        'Soldiers':                                        ('Soldiers: Heroes of World War II', None, 'D3D8'),
        'sonic2app':                                       ('Sonic Adventure 2', None, 'D3D9'), # With the SA2 Render Fix mod
        'Soulstorm':                                       ('Warhammer 40,000: Dawn of War: Soulstorm', None, 'D3D9'),
        'SpaceHulkGame-Win64-Shipping':                    ('Space Hulk: Deathwing', None, 'D3D11'),
        'SpaceMarine':                                     ('Warhammer 40,000: Space Marine', None, 'D3D9'),
        'SpecOpsTheLine':                                  ('Spec Ops: The Line', None, 'D3D9'),
        'SPEED2':                                          ('Need for Speed: Underground 2', None, 'D3D9'),
        'SpellForce':                                      ('SpellForce - Platinum Edition', None, 'D3D9'),
        'SpellForce2':                                     ('SpellForce 2: Shadow Wars', None, 'D3D9'),
        'Spelunky':                                        ('Spelunky Classic', None, 'D3D8'),
        'SporeApp':                                        ('Spore', None, 'D3D9'),
        'Squad22':                                         ('Meridian: Squad 22', None, 'D3D11'),
        'sr2':                                             ('Legacy of Kain: Soul Reaver 2', None, 'D3D8'),
        'SR2_pc':                                          ('Saints Row 2', None, 'D3D9'),
        'SRS':                                             ('Street Racing Syndicate', None, 'D3D9'),
        'SS3Game':                                         ('Sudden Strike 3: Arms for Victory', None, 'D3D9'),
        'StarpointGemini2':                                ('Starpoint Gemini 2', None, 'D3D11'),
        'StarWolves':                                      ('Star Wolves', None, 'D3D9'),
        'stdrt':                                           ('Castlevania: The Lecarde Chronicles', 'https://castlevaniafan.fandom.com/wiki/Castlevania:_The_Lecarde_Chronicles', 'D3D9'),
        'stdrt_':                                          ('Castlevania: The Lecarde Chronicles 2', 'https://castlevaniafan.fandom.com/wiki/Castlevania:_The_Lecarde_Chronicles', 'D3D9'),
        'SteelRats-Win64-Shipping':                        ('Steel Rats', None, 'D3D11'),
        'StreetFighterV':                                  ('Street Fighter V', None, 'D3D11'),
        'SUDEKI':                                          ('Sudeki', None, 'D3D9'),
        'SuperMeatBoy':                                    ('Super Meat Boy', None, 'D3D9'),
        'SupremeCommander':                                ('Supreme Commander', None, 'D3D9'),
        'SupremeCommander_':                               ('Supreme Commander: Forged Alliance', None, 'D3D9'),
        'SupremeCommander2':                               ('Supreme Commander 2', None, 'D3D9'),
        'SupremeRuler2020GC':                              ('Supreme Ruler 2020', None, 'D3D8'),
        'SupremeRuler':                                    ('Supreme Ruler 2010', None, 'D3D9'),
        'sw':                                              ('Shadow Warrior (2013)', None, 'D3D9'),
        'sw.x64':                                          ('Shadow Warrior (2013)', None, 'D3D11'),
        'Swat4':                                           ('SWAT 4', None, 'D3D9'),
        'sweaw':                                           ('Star Wars: Empire at War', None, 'D3D9'),
        'swine':                                           ('S.W.I.N.E.', None, 'D3D8'),
        'swine_':                                          ('S.W.I.N.E. HD Remaster', None, 'D3D9'),
        'SWTFU':                                           ('Star Wars: The Force Unleashed', None, 'D3D9'),
        'SWTFU2':                                          ('Star Wars: The Force Unleashed II', None, 'D3D9'),
        'Symmetry':                                        (None, None, 'D3D9Ex'),
        'SystemReShock-Win64-Shipping':                    ('System Shock (2023)', None, 'D3D11'),
        'T3Main':                                          ('Thief: Deadly Shadows', None, 'D3D8'),
        'Talos':                                           ('The Talos Principle', None, 'D3D11'),
        'Teslagrad':                                       (None, None, 'D3D9'),
        'TESV':                                            ('The Elder Scrolls V: Skyrim', None, 'D3D9'),
        'Texas HoldEm':                                    ('Telltale Texas Hold \'Em', None, 'D3D8'),
        'TFT':                                             ('The First Templar', None, 'D3D9'),
        'tharsis':                                         ('Tharsis', None, 'D3D9'),
        'The ABC Murders':                                 ('Agatha Christie: The ABC Murders', None, 'D3D11'),
        'The ABC Murders_':                                ('Agatha Christie: The ABC Murders', None, 'D3D9'),
        'the last tinker':                                 ('The Last Tinker: City of Colors', None, 'D3D9'),
        'The Whisperer':                                   (None, None, 'D3D11'),
        'TheBeastInside-Win64-Shipping':                   ('The Beast Inside', None, 'D3D11'),
        'TheBureau':                                       ('The Bureau: XCOM Declassified', None, 'D3D9'),
        'TheIOfTheDragon':                                 ('The I of the Dragon', None, 'D3D8'),
        'theHunter':                                       ('The Hunter', None, 'D3D9'),
        'TheObserver-Win64-Shipping':                      ('Observer', None, 'D3D11'),
        'TheSpiritAndTheMouse':                            ('The Spirit and the Mouse', None, 'D3D11'),
        'TheSurge':                                        ('The Surge', None, 'D3D11'),
        'This War of Mine':                                (None, None, 'D3D9'),
        'TimeShift':                                       (None, None, 'D3D9'),
        'Titanfall2':                                      ('Titanfall 2', None, 'D3D11'),
        'TOD':                                             ('Total Overdose: A Gunslinger\'s Tale in Mexico', None, 'D3D9'),
        'ToEEa':                                           ('The Temple of Elemental Evil', None, 'D3D8'),
        'TombRaider':                                      ('Tomb Raider (2013)', None, 'D3D11'),
        'TonightWeRiot_PC':                                ('Tonight We Riot', None, 'D3D11'),
        'TopSpin':                                         ('Top Spin', None, 'D3D8'),
        'Torchlight':                                      (None, None, 'D3D9'),
        'Torchlight2':                                     ('Torchlight II', None, 'D3D9'),
        'tra':                                             ('Tomb Raider: Anniversary', None, 'D3D9'),
        'Trailblazers':                                    (None, None, 'D3D11'),
        'trine':                                           ('Trine', None, 'D3D9'),
        'trine1_32bit':                                    ('Trine Enchanted Edition', None, 'D3D9'),
        'trine2_32bit':                                    ('Trine 2', None, 'D3D9'),
        'trl':                                             ('Tomb Raider: Legend', None, 'D3D9'),
        'Troy':                                            ('A Total War Saga: Troy', None, 'D3D11'),
        'tru':                                             ('Tomb Raider: Underworld', None, 'D3D9'),
        'Truberbrook':                                     ('Trüberbrook', None, 'D3D11'),
        'Tunic':                                           (None, None, 'D3D11'),
        'Underspace':                                      (None, None, 'D3D11'),
        'VambraceColdSoul':                                ('Vambrace: Cold Soul', None, 'D3D11'),
        'Vampire':                                         ('Vampire: The Masquerade - Bloodlines', None, 'D3D9'),
        'VampireSurvivors':                                ('Vampire Survivors', None, 'D3D11'),
        'VanHelsing_x64':                                  ('The Incredible Adventures of Van Helsing: Final Cut', None, 'D3D9'),
        'VanHelsing_x64_11':                               ('The Incredible Adventures of Van Helsing: Final Cut', None, 'D3D11'),
        'vermintide2':                                     ('Warhammer: Vermintide 2', None, 'D3D11'),
        'vietcong':                                        ('Vietcong', None, 'D3D9'),
        'Vietnam':                                         ('Line of Sight: Vietnam', None, 'D3D9'),
        'W40k':                                            ('Warhammer 40,000: Dawn of War', None, 'D3D9'),
        'war3':                                            ('Warcraft III: Reign of Chaos', None, 'D3D8'),
        'WarChess':                                        ('War Chess', None, 'D3D8'),
        'Warrior_Kings_Battles':                           ('Warrior Kings: Battles', None, 'D3D8'),
        'warrior_kings':                                   ('Warrior Kings', None, 'D3D8'),
        'WA':                                              ('Worms Armageddon', None, 'D3D9'),
        'wic':                                             ('World in Conflict', None, 'D3D9'),
        'witcher2':                                        ('The Witcher 2: Assassins of Kings', None, 'D3D9'),
        'witcher3':                                        ('The Witcher 3: Wild Hunt', None, 'D3D11'),
        'witcher':                                         ('The Witcher', None, 'D3D9'),
        'witness64_d3d11':                                 ('The Witness', None, 'D3D11'),
        'WL2':                                             ('Wasteland 2', None, 'D3D11'), # Director's Cut
        'WL2_':                                            ('Wasteland 2', None, 'D3D9'), # Director's Cut
        'Wow':                                             ('World of Warcraft', None, 'D3D11'),
        'Wow_':                                            ('World of Warcraft', None, 'D3D9'), # 3.3.5a Warmane
        'WR2_PC':                                          ('World Racing 2: Champion Edition', None, 'D3D9Ex'),
        'Wreckfest_x64':                                   ('Wreckfest', None, 'D3D11'),
        'X2':                                              ('X2: The Threat', None, 'D3D8'),
        'XANADU':                                          ('Xanadu Next', None, 'D3D8'),
        'XComGame':                                        ('XCOM: Enemy Unknown', None, 'D3D9'),
        'yaga':                                            ('Yaga', None, 'D3D11'),
        'Yakuza0':                                         ('Yakuza 0', None, 'D3D11'),
        'ys6_win':                                         ('Ys VI: The Ark of Napishtim', None, 'D3D8'),
        'ysf_win':                                         ('Ys: The Oath in Felghana', None, 'D3D8'),
        'z2':                                              ('Z: Steel Soldiers', None, 'D3D8'),
        'zapper':                                          ('Zapper: One Wicked Cricket', None, 'D3D8'),
        'ZombieShooter':                                   ('Zombie Shooter', None, 'D3D8'),
        'ZWEI2P':                                          ('Zwei: The Ilvard Insurrection', None, 'D3D8')
    }

    @classmethod
    def get(cls, trace_name):
        return cls.trace_application_names.get(trace_name, None)

